name: flutter_string_extractor
version: 0.1.1
description: Extract .tr and tr() strings from Flutter project and save them as JSON
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  glob: ^2.1.1
  args: ^2.3.0
repository: https://github.com/Reshail1/flutter_string_extractor.git